{% set version = "__VERSION__" %} # To be replaced in gh action

package:
  name: intake-dataframe-catalog
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/i/intake-dataframe-catalog/intake_dataframe_catalog-{{ version }}.tar.gz"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - versioneer
  run:
    - python >=3.9
    - intake
    - pandas

test:
  imports:
    - intake_dataframe_catalog

about:
  home: https://github.com/ACCESS-NRI/intake-dataframe-catalog
  license: Apache Software
  license_family: APACHE
  summary: "An intake driver for a searchable table of intake catalogs and associated metadata"
  doc_url: https://intake-dataframe-catalog.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - dougiesquire
