name: intake-df-cat-test
channels:
  - conda-forge
dependencies:
  - black
  - ruff
  - intake
  - intake-esm
  - pytest
  - python=3.9
  - pip
  - pip:
    - codecov
    - pre-commit
    - pytest-cov
