name: intake-df-cat-test
channels:
  - conda-forge
dependencies:
  - black
  - intake<2.0.0
  - intake-esm
  - pytest
  - python=3.9
  - pip
  - pip:
    - build
    - ruff
    - codecov
    - pre-commit
    - pytest-cov
    - twine
