name: intake-df-cat-test
channels:
  - conda-forge
dependencies:
  - black
  - intake
  - intake-esm
  - pytest
  - python=3.10
  - pip
  - pip:
    - ruff
    - codecov
    - pre-commit
    - pytest-cov
