name: intake-df-cat-test
channels:
  - conda-forge
dependencies:
  - black
  - intake>=0.7
  - intake-esm
  - polars>=1.12
  - pytest
  - python=3.10
  - pip
  - pip:
    - build
    - ruff
    - codecov
    - pre-commit
    - pytest-cov
    - twine
