name: intake-df-cat-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - ipython
  - nbsphinx
  - numpydoc
  - sphinx
  - sphinx-autobuild
  - black
  - flake8
  - pip
  - pip:
    - sphinx_rtd_theme
    - sphinxcontrib-napoleon
    - sphinx-autoapi
    - sphinx-copybutton
    - pre-commit
