name: intake-df-cat-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - ipython
  - numpydoc
  - sphinx
  - sphinx-autobuild
  - pandas
  - black
  - ruff
  - pip
  - pip:
    - sphinx-book-theme
    - sphinxcontrib-napoleon
    - sphinx-copybutton
    - myst-nb
    - pre-commit
    - -e ..
