name: conda build

on: [push, pull_request]

jobs:
  build:
    name: conda build with Python ${{ matrix.python-version }}
    if: github.repository == 'ACCESS-NRI/intake-dataframe-catalog' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: .conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload the conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: .conda
          python-version: ${{ matrix.python-version }}
          user: dougiesquire
          label: main
          token: ${{ secrets.ANACONDA_TOKEN }}

